/**
 * Countries & Continents — Canonical Reference Data
 * ══════════════════════════════════════════════════
 * Single source of truth for all country ↔ continent mappings.
 *
 * Consumed by:
 *   - src/components/shared/form-fields.jsx  (COUNTRIES array, CountrySelect)
 *   - src/components/phases/deal-form.jsx    (manufacturing country, export regions)
 *   - src/components/phases/supplier-profile-form.jsx (countries served, excluded)
 *
 * Each entry: { value, label, iso, continent }
 *   value     — Display name (used as form value)
 *   label     — Display name (same as value; kept for select-component compat)
 *   iso       — ISO 3166-1 alpha-2 code (lowercase)
 *   continent — One of: Africa, Antarctica, Asia, Europe, North America,
 *               Oceania, South America
 *
 * Prioritised markets are listed first for quick access in dropdowns.
 */

/* ─── Continent constants ─── */
export const CONTINENTS = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
];

/* ─── Full country list with continent associations ─── */
export const COUNTRIES = [
  /* ─── Prioritised markets (kept at top for quick access) ─── */
  { value: "United Kingdom", label: "United Kingdom", iso: "gb", continent: "Europe" },
  { value: "United States", label: "United States", iso: "us", continent: "North America" },
  { value: "Germany", label: "Germany", iso: "de", continent: "Europe" },
  { value: "France", label: "France", iso: "fr", continent: "Europe" },
  { value: "Italy", label: "Italy", iso: "it", continent: "Europe" },
  { value: "Spain", label: "Spain", iso: "es", continent: "Europe" },
  { value: "Netherlands", label: "Netherlands", iso: "nl", continent: "Europe" },
  { value: "Belgium", label: "Belgium", iso: "be", continent: "Europe" },
  { value: "Canada", label: "Canada", iso: "ca", continent: "North America" },
  { value: "Australia", label: "Australia", iso: "au", continent: "Oceania" },
  { value: "Poland", label: "Poland", iso: "pl", continent: "Europe" },
  { value: "Sweden", label: "Sweden", iso: "se", continent: "Europe" },
  { value: "Norway", label: "Norway", iso: "no", continent: "Europe" },
  { value: "Denmark", label: "Denmark", iso: "dk", continent: "Europe" },
  { value: "Ireland", label: "Ireland", iso: "ie", continent: "Europe" },
  { value: "Portugal", label: "Portugal", iso: "pt", continent: "Europe" },
  { value: "Greece", label: "Greece", iso: "gr", continent: "Europe" },
  { value: "Austria", label: "Austria", iso: "at", continent: "Europe" },
  { value: "Switzerland", label: "Switzerland", iso: "ch", continent: "Europe" },

  /* ─── All other countries (alphabetical) ─── */
  { value: "Afghanistan", label: "Afghanistan", iso: "af", continent: "Asia" },
  { value: "Albania", label: "Albania", iso: "al", continent: "Europe" },
  { value: "Algeria", label: "Algeria", iso: "dz", continent: "Africa" },
  { value: "Andorra", label: "Andorra", iso: "ad", continent: "Europe" },
  { value: "Angola", label: "Angola", iso: "ao", continent: "Africa" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda", iso: "ag", continent: "North America" },
  { value: "Argentina", label: "Argentina", iso: "ar", continent: "South America" },
  { value: "Armenia", label: "Armenia", iso: "am", continent: "Asia" },
  { value: "Azerbaijan", label: "Azerbaijan", iso: "az", continent: "Asia" },
  { value: "Bahamas", label: "Bahamas", iso: "bs", continent: "North America" },
  { value: "Bahrain", label: "Bahrain", iso: "bh", continent: "Asia" },
  { value: "Bangladesh", label: "Bangladesh", iso: "bd", continent: "Asia" },
  { value: "Barbados", label: "Barbados", iso: "bb", continent: "North America" },
  { value: "Belarus", label: "Belarus", iso: "by", continent: "Europe" },
  { value: "Belize", label: "Belize", iso: "bz", continent: "North America" },
  { value: "Benin", label: "Benin", iso: "bj", continent: "Africa" },
  { value: "Bhutan", label: "Bhutan", iso: "bt", continent: "Asia" },
  { value: "Bolivia", label: "Bolivia", iso: "bo", continent: "South America" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", iso: "ba", continent: "Europe" },
  { value: "Botswana", label: "Botswana", iso: "bw", continent: "Africa" },
  { value: "Brazil", label: "Brazil", iso: "br", continent: "South America" },
  { value: "Brunei", label: "Brunei", iso: "bn", continent: "Asia" },
  { value: "Bulgaria", label: "Bulgaria", iso: "bg", continent: "Europe" },
  { value: "Burkina Faso", label: "Burkina Faso", iso: "bf", continent: "Africa" },
  { value: "Burundi", label: "Burundi", iso: "bi", continent: "Africa" },
  { value: "Cabo Verde", label: "Cabo Verde", iso: "cv", continent: "Africa" },
  { value: "Cambodia", label: "Cambodia", iso: "kh", continent: "Asia" },
  { value: "Cameroon", label: "Cameroon", iso: "cm", continent: "Africa" },
  { value: "Central African Republic", label: "Central African Republic", iso: "cf", continent: "Africa" },
  { value: "Chad", label: "Chad", iso: "td", continent: "Africa" },
  { value: "Chile", label: "Chile", iso: "cl", continent: "South America" },
  { value: "China", label: "China", iso: "cn", continent: "Asia" },
  { value: "Colombia", label: "Colombia", iso: "co", continent: "South America" },
  { value: "Comoros", label: "Comoros", iso: "km", continent: "Africa" },
  { value: "Congo (Brazzaville)", label: "Congo (Brazzaville)", iso: "cg", continent: "Africa" },
  { value: "Congo (Kinshasa)", label: "Congo (Kinshasa)", iso: "cd", continent: "Africa" },
  { value: "Costa Rica", label: "Costa Rica", iso: "cr", continent: "North America" },
  { value: "Croatia", label: "Croatia", iso: "hr", continent: "Europe" },
  { value: "Cuba", label: "Cuba", iso: "cu", continent: "North America" },
  { value: "Cyprus", label: "Cyprus", iso: "cy", continent: "Europe" },
  { value: "Czech Republic", label: "Czech Republic", iso: "cz", continent: "Europe" },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire", iso: "ci", continent: "Africa" },
  { value: "Djibouti", label: "Djibouti", iso: "dj", continent: "Africa" },
  { value: "Dominica", label: "Dominica", iso: "dm", continent: "North America" },
  { value: "Dominican Republic", label: "Dominican Republic", iso: "do", continent: "North America" },
  { value: "East Timor", label: "East Timor", iso: "tl", continent: "Asia" },
  { value: "Ecuador", label: "Ecuador", iso: "ec", continent: "South America" },
  { value: "Egypt", label: "Egypt", iso: "eg", continent: "Africa" },
  { value: "El Salvador", label: "El Salvador", iso: "sv", continent: "North America" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", iso: "gq", continent: "Africa" },
  { value: "Eritrea", label: "Eritrea", iso: "er", continent: "Africa" },
  { value: "Estonia", label: "Estonia", iso: "ee", continent: "Europe" },
  { value: "Eswatini", label: "Eswatini", iso: "sz", continent: "Africa" },
  { value: "Ethiopia", label: "Ethiopia", iso: "et", continent: "Africa" },
  { value: "Fiji", label: "Fiji", iso: "fj", continent: "Oceania" },
  { value: "Finland", label: "Finland", iso: "fi", continent: "Europe" },
  { value: "Gabon", label: "Gabon", iso: "ga", continent: "Africa" },
  { value: "Gambia", label: "Gambia", iso: "gm", continent: "Africa" },
  { value: "Georgia", label: "Georgia", iso: "ge", continent: "Asia" },
  { value: "Ghana", label: "Ghana", iso: "gh", continent: "Africa" },
  { value: "Grenada", label: "Grenada", iso: "gd", continent: "North America" },
  { value: "Guatemala", label: "Guatemala", iso: "gt", continent: "North America" },
  { value: "Guinea", label: "Guinea", iso: "gn", continent: "Africa" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", iso: "gw", continent: "Africa" },
  { value: "Guyana", label: "Guyana", iso: "gy", continent: "South America" },
  { value: "Haiti", label: "Haiti", iso: "ht", continent: "North America" },
  { value: "Honduras", label: "Honduras", iso: "hn", continent: "North America" },
  { value: "Hungary", label: "Hungary", iso: "hu", continent: "Europe" },
  { value: "Iceland", label: "Iceland", iso: "is", continent: "Europe" },
  { value: "India", label: "India", iso: "in", continent: "Asia" },
  { value: "Indonesia", label: "Indonesia", iso: "id", continent: "Asia" },
  { value: "Iran", label: "Iran", iso: "ir", continent: "Asia" },
  { value: "Iraq", label: "Iraq", iso: "iq", continent: "Asia" },
  { value: "Israel", label: "Israel", iso: "il", continent: "Asia" },
  { value: "Jamaica", label: "Jamaica", iso: "jm", continent: "North America" },
  { value: "Japan", label: "Japan", iso: "jp", continent: "Asia" },
  { value: "Jordan", label: "Jordan", iso: "jo", continent: "Asia" },
  { value: "Kazakhstan", label: "Kazakhstan", iso: "kz", continent: "Asia" },
  { value: "Kenya", label: "Kenya", iso: "ke", continent: "Africa" },
  { value: "Kiribati", label: "Kiribati", iso: "ki", continent: "Oceania" },
  { value: "Kosovo", label: "Kosovo", iso: "xk", continent: "Europe" },
  { value: "Kuwait", label: "Kuwait", iso: "kw", continent: "Asia" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", iso: "kg", continent: "Asia" },
  { value: "Laos", label: "Laos", iso: "la", continent: "Asia" },
  { value: "Latvia", label: "Latvia", iso: "lv", continent: "Europe" },
  { value: "Lebanon", label: "Lebanon", iso: "lb", continent: "Asia" },
  { value: "Lesotho", label: "Lesotho", iso: "ls", continent: "Africa" },
  { value: "Liberia", label: "Liberia", iso: "lr", continent: "Africa" },
  { value: "Libya", label: "Libya", iso: "ly", continent: "Africa" },
  { value: "Liechtenstein", label: "Liechtenstein", iso: "li", continent: "Europe" },
  { value: "Lithuania", label: "Lithuania", iso: "lt", continent: "Europe" },
  { value: "Luxembourg", label: "Luxembourg", iso: "lu", continent: "Europe" },
  { value: "Madagascar", label: "Madagascar", iso: "mg", continent: "Africa" },
  { value: "Malawi", label: "Malawi", iso: "mw", continent: "Africa" },
  { value: "Malaysia", label: "Malaysia", iso: "my", continent: "Asia" },
  { value: "Maldives", label: "Maldives", iso: "mv", continent: "Asia" },
  { value: "Mali", label: "Mali", iso: "ml", continent: "Africa" },
  { value: "Malta", label: "Malta", iso: "mt", continent: "Europe" },
  { value: "Marshall Islands", label: "Marshall Islands", iso: "mh", continent: "Oceania" },
  { value: "Mauritania", label: "Mauritania", iso: "mr", continent: "Africa" },
  { value: "Mauritius", label: "Mauritius", iso: "mu", continent: "Africa" },
  { value: "Mexico", label: "Mexico", iso: "mx", continent: "North America" },
  { value: "Micronesia", label: "Micronesia", iso: "fm", continent: "Oceania" },
  { value: "Moldova", label: "Moldova", iso: "md", continent: "Europe" },
  { value: "Monaco", label: "Monaco", iso: "mc", continent: "Europe" },
  { value: "Mongolia", label: "Mongolia", iso: "mn", continent: "Asia" },
  { value: "Montenegro", label: "Montenegro", iso: "me", continent: "Europe" },
  { value: "Morocco", label: "Morocco", iso: "ma", continent: "Africa" },
  { value: "Mozambique", label: "Mozambique", iso: "mz", continent: "Africa" },
  { value: "Myanmar", label: "Myanmar", iso: "mm", continent: "Asia" },
  { value: "Namibia", label: "Namibia", iso: "na", continent: "Africa" },
  { value: "Nauru", label: "Nauru", iso: "nr", continent: "Oceania" },
  { value: "Nepal", label: "Nepal", iso: "np", continent: "Asia" },
  { value: "New Zealand", label: "New Zealand", iso: "nz", continent: "Oceania" },
  { value: "Nicaragua", label: "Nicaragua", iso: "ni", continent: "North America" },
  { value: "Niger", label: "Niger", iso: "ne", continent: "Africa" },
  { value: "Nigeria", label: "Nigeria", iso: "ng", continent: "Africa" },
  { value: "North Korea", label: "North Korea", iso: "kp", continent: "Asia" },
  { value: "North Macedonia", label: "North Macedonia", iso: "mk", continent: "Europe" },
  { value: "Oman", label: "Oman", iso: "om", continent: "Asia" },
  { value: "Pakistan", label: "Pakistan", iso: "pk", continent: "Asia" },
  { value: "Palau", label: "Palau", iso: "pw", continent: "Oceania" },
  { value: "Palestine", label: "Palestine", iso: "ps", continent: "Asia" },
  { value: "Panama", label: "Panama", iso: "pa", continent: "North America" },
  { value: "Papua New Guinea", label: "Papua New Guinea", iso: "pg", continent: "Oceania" },
  { value: "Paraguay", label: "Paraguay", iso: "py", continent: "South America" },
  { value: "Peru", label: "Peru", iso: "pe", continent: "South America" },
  { value: "Philippines", label: "Philippines", iso: "ph", continent: "Asia" },
  { value: "Qatar", label: "Qatar", iso: "qa", continent: "Asia" },
  { value: "Romania", label: "Romania", iso: "ro", continent: "Europe" },
  { value: "Russia", label: "Russia", iso: "ru", continent: "Europe" },
  { value: "Rwanda", label: "Rwanda", iso: "rw", continent: "Africa" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", iso: "kn", continent: "North America" },
  { value: "Saint Lucia", label: "Saint Lucia", iso: "lc", continent: "North America" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", iso: "vc", continent: "North America" },
  { value: "Samoa", label: "Samoa", iso: "ws", continent: "Oceania" },
  { value: "San Marino", label: "San Marino", iso: "sm", continent: "Europe" },
  { value: "São Tomé and Príncipe", label: "São Tomé and Príncipe", iso: "st", continent: "Africa" },
  { value: "Saudi Arabia", label: "Saudi Arabia", iso: "sa", continent: "Asia" },
  { value: "Senegal", label: "Senegal", iso: "sn", continent: "Africa" },
  { value: "Serbia", label: "Serbia", iso: "rs", continent: "Europe" },
  { value: "Seychelles", label: "Seychelles", iso: "sc", continent: "Africa" },
  { value: "Sierra Leone", label: "Sierra Leone", iso: "sl", continent: "Africa" },
  { value: "Singapore", label: "Singapore", iso: "sg", continent: "Asia" },
  { value: "Slovakia", label: "Slovakia", iso: "sk", continent: "Europe" },
  { value: "Slovenia", label: "Slovenia", iso: "si", continent: "Europe" },
  { value: "Solomon Islands", label: "Solomon Islands", iso: "sb", continent: "Oceania" },
  { value: "Somalia", label: "Somalia", iso: "so", continent: "Africa" },
  { value: "South Africa", label: "South Africa", iso: "za", continent: "Africa" },
  { value: "South Korea", label: "South Korea", iso: "kr", continent: "Asia" },
  { value: "South Sudan", label: "South Sudan", iso: "ss", continent: "Africa" },
  { value: "Sri Lanka", label: "Sri Lanka", iso: "lk", continent: "Asia" },
  { value: "Sudan", label: "Sudan", iso: "sd", continent: "Africa" },
  { value: "Suriname", label: "Suriname", iso: "sr", continent: "South America" },
  { value: "Syria", label: "Syria", iso: "sy", continent: "Asia" },
  { value: "Taiwan", label: "Taiwan", iso: "tw", continent: "Asia" },
  { value: "Tajikistan", label: "Tajikistan", iso: "tj", continent: "Asia" },
  { value: "Tanzania", label: "Tanzania", iso: "tz", continent: "Africa" },
  { value: "Thailand", label: "Thailand", iso: "th", continent: "Asia" },
  { value: "Togo", label: "Togo", iso: "tg", continent: "Africa" },
  { value: "Tonga", label: "Tonga", iso: "to", continent: "Oceania" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago", iso: "tt", continent: "North America" },
  { value: "Tunisia", label: "Tunisia", iso: "tn", continent: "Africa" },
  { value: "Turkey", label: "Turkey", iso: "tr", continent: "Asia" },
  { value: "Turkmenistan", label: "Turkmenistan", iso: "tm", continent: "Asia" },
  { value: "Tuvalu", label: "Tuvalu", iso: "tv", continent: "Oceania" },
  { value: "Uganda", label: "Uganda", iso: "ug", continent: "Africa" },
  { value: "Ukraine", label: "Ukraine", iso: "ua", continent: "Europe" },
  { value: "United Arab Emirates", label: "United Arab Emirates", iso: "ae", continent: "Asia" },
  { value: "Uruguay", label: "Uruguay", iso: "uy", continent: "South America" },
  { value: "Uzbekistan", label: "Uzbekistan", iso: "uz", continent: "Asia" },
  { value: "Vanuatu", label: "Vanuatu", iso: "vu", continent: "Oceania" },
  { value: "Vatican City", label: "Vatican City", iso: "va", continent: "Europe" },
  { value: "Venezuela", label: "Venezuela", iso: "ve", continent: "South America" },
  { value: "Vietnam", label: "Vietnam", iso: "vn", continent: "Asia" },
  { value: "Yemen", label: "Yemen", iso: "ye", continent: "Asia" },
  { value: "Zambia", label: "Zambia", iso: "zm", continent: "Africa" },
  { value: "Zimbabwe", label: "Zimbabwe", iso: "zw", continent: "Africa" },
];

/* ─── Utility: group countries by continent ─── */
export const COUNTRIES_BY_CONTINENT = CONTINENTS.reduce((acc, continent) => {
  acc[continent] = COUNTRIES.filter((c) => c.continent === continent);
  return acc;
}, {});

/* ─── Utility: get continent for a country value ─── */
export function getContinentForCountry(countryValue) {
  const entry = COUNTRIES.find((c) => c.value === countryValue);
  return entry?.continent ?? null;
}

/* ─── Utility: get all countries for a continent ─── */
export function getCountriesForContinent(continent) {
  return COUNTRIES.filter((c) => c.continent === continent);
}
