"use client";

import { memo, useMemo } from "react";

/* ═══════════════════════════════════════
   BITMAP-ENCODED WORLD MAP
   320×160 grid, 1 bit per cell, base64
   Generated from world-atlas/land-50m.json
   using d3-geo spherical point-in-polygon

   PERF NOTE: The original version rendered each
   dot as its own <circle> DOM node (~16k dots × 3
   copies = ~50k elements). This version batches
   all dots into a single <path> per copy — 3 DOM
   nodes total instead of 50k.
   ═══════════════════════════════════════ */
const MAP_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALfsAAD///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMH/+D/////6YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+A/4f//////8AAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAb9/AD//////4AAAAPjAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAATfw///////4AAAAB4gAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAOAAAA/wH///////gAAAAYAAAAAAAAAAAQ8AAAAAAAAAAAAAAAAAAAA+AADAEAAH/////wAAAAAAAAAAAYAAAAP//AAAAAAAAAAAAAAAAAAABwAG/+AAAf////8AAAAAAAAAAA8AAAH///wAAAAAAAAAAAAAAAAAD+AQ94ygAAD////3AAAAAAAAAAA4AAAO///OgIABgAAAAAAAAAAAAB9+sPY7zgAAf///9AAAAAAAAAAAYAHhP//////wAeAAAAAAAAAAAAAMH/gmPf7gAB////wAAAAAAAAAAGAD2///////+bf/AAAAAAAD/AAAgAH+Dwf//AAf///QAAAAAAF8AAAAA8////////////8AAAAAH//+f/+D7huDxfoAB///4AAAAAB//8ACAPHL////////////vz/AAH//////8Bgf44B+AB//+AAAAAAAf//8Y///7///////////////+AD////////f9/2Af8A///AAAAAAA////m///5////////////////8AP//////////bAPzAH/+AAvgAAAf//4P////////////////////fg///////////9wf/AAf8AAP4AAAP+P+f////////////////////gQPf/////////4IEH4AP/AAAwAAAP/P//////////////////////4AAH/////////8BhIaAB/AAAAAAAf+H////////////////////7/4AAf/////////+AAfAAAPwAAAAAAN/h///////////////////+M/wAAH/3D///////AAH8IAAMAAAAAAB/8MP//////////////////A4QAAG/4AB//////wAD/iAAAAAAAAAAe/B/////////////////wDA4AAAAD8AAH//////AAf/4AAAAAAABAAPgP////////////////4AA8AAAAAAAAAP/////+AD/8AAAAAAAAcAZ4f////////////////4AAfgAAAABAAAH//////8B//wAAAAAAALAGoH////////////////8AAPwAAAADAAAAP//////5///gAAAAAAGYAgT/////////////////AAD8AAAAEAAAAJ//////+P//cAAAAAAHnA///////////////////+AAcAAAAMAAAAAH//////j///AAAAAABz4////////////////////4AGAAAAAAAAAAD//////////AAAAAAAA+////////////////////7ABAAAAAAAAAAAf////////gEAAAAAAAAf///////////////////+wAAAAAAAAAAAABf///////uDwAAAAAAAf////////////////////qAAAAAAAAAAAAAf////////B+AAAAAAAf////////////////////yAAAAAAAAAAAAAD////////wAgAAAAAAD/////z/5////////////4wAAAAAAAAAAAAA///////39gAAAAAAAAf/v/8Z/wf///////////8AAAAAAAAAAAAAAP///////9gAAAAAAAAH/4//AP8f///////////+CAAAAAAAAAAAAAH///////4AAAAAAAAD/5HH/gA/D////////////A4AAAAAAAAAAAAB///////+AAAAAAAAA/+A4f4AH4f//////////8AgAAAAAAAAAAAAAP//////+AAAAAAAAAP+ADn//z/B//////////+AAAAAAAAAAAAAAAD///////AAAAAAAAAD/AYIz///w/////////83ADAAAAAAAAAAAAAA///////gAAAAAAAAA/wACMP//4P////////+BwAwAAAAAAAAAAAAAH//////wAAAAAAAAAP4AHDj///D/////////0GAYAAAAAAAAAAAAAA//////8AAAAAAAAAAwP8AILP///////////+DgeAAAAAAAAAAAAAAH//////AAAAAAAAAAAf/ABAD////////////A4/gAAAAAAAAAAAAAA//////gAAAAAAAAAD//gAAA////////////4AzAAAAAAAAAAAAAAAD/////wAAAAAAAAAD//8AAAf///////////+AYAAAAAAAAAAAAAAAA/////wAAAAAAAAAA///8OAH////////////wCAAAAAAAAAAAAAAAAF////8AAAAAAAAAAf///z//////////////8AAAAAAAAAAAAAAAAABP//eLAAAAAAAAAAH////////n//////////AAAAAAAAAAAAAAAAAAJ//gAQAAAAAAAAAD//////v/5//////////wAAAAAAAAAAAAAAAAADP/gAGAAAAAAAAAD//////8//H/////////4AAAAAAAAAAAAAAAAAAJ/4ABkAAAAAAAAB///////P/4H////////+AAAAAAAAAAAAAAAAAACP+AAIAAAAAAAAAf//////5//ENf///////AAAAAAAAAAAAAAAAAAAR/gAAAAAAAAAAAP///////P/zgD///////kAAAAAAAAAAAAAAAAAACP4ABAAAAAAAAAD///////z//+Af//3///xAAAAAAAAAAAAAAAAAAAD+AAGAAAAAAAAB///////+f//gDf/8///AAAAAAAAAAAAAIAAAAAAA/wOAYAAAAAAAAf///////n//wAH/4P/4AAAAAAAAAAAAABAAAAAAAP8HAAYAAAAAAAH///////4//4AB/8B/8YAAAAAAAAAAAAAAAAAAAAA/xwALgAAAAAAA////////H/8AAf+AP/EAQAAAAAAAAAAAAAAAAAAAD/8AAAAAAAAAAP///////4/+AAH/AD/4AGAAAAAAAAAAAAAAAAAAAAP+AAABAAAAAAH///////+P+AAB/AAn/ADgAAAAAAAAAAAAAAAAAAAAH/AAAAAAAAAB////////z+AAAPgAB/4AQAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAf///////++AAAD4AAf+AEAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAH////////0AAAAeAAC/gBAAAAAAAAAAAAAAAAAAAAAAHACAAAAAAAA////////8BAAAHgAAn4AJAAAAAAAAAAAAAAAAAAAAAAwH4MAAAAAAH////////vgAAA4AAA8ADAAAAAAAAAAAAAAAAAAAAAAGB3/AAAAAAA/////////4AAANAAAEAAAAAAAAAAAAAAAAAAAAAAAAA6//oAAAAAAP////////+AAACQABgAAHAAAAAAAAAAAAAAAAAAAAAACf//AAAAAAB/////////AAAAGAAAAAC4AAAAAAAAAAAAAAAAAAAAAAH//4AAAAAAH/j//////wAAABAABgAYMAAAAAAAAAAAAAAAAAAAAAAB///4AAAAAA5gf/////4AAAAAAGcAHAAAAAAAAAAAAAAAAAAAAAAAAf///gAAAAAAAAf////8AAAAAAAzAHgAAAAAAAAAAAAAAAAAAAAAAAH///4AAAAAAAAH////+AAAAAAAGwH4AAAAAAAAAAAAAAAAAAAAAAAD////AAAAAAAAB/////AAAAAAAAyF+AQAAAAAAAAAAAAAAAAAAAAAB////wAAAAAAAA/////gAAAAAAAPB/nkAAAAAAAAAAAAAAAAAAAAAAf///2AAAAAAAAP////wAAAAAAABwfyAEAAAAAAAAAAAAAAAAAAAAAP////cAAAAAAAD////4AAAAAAAAOD4wRiAAAAAAAAAAAAAAAAAAAAB/////YAAAAAAAf///8AAAAAAAAD4+KAd8AAAAAAAAAAAAAAAAAAAA//////wAAAAAAD///+AAAAAAAAAcACgC/4AAAAAAAAAAAAAAAAAAAP/////+AAAAAAAf///gAAAAAAAADAAgAD/CAAAAAAAAAAAAAAAAAAD//////4AAAAAAH///4AAAAAAAAAMAAAEf5AAAAAAAAAAAAAAAAAAAf/////+AAAAAAB///+AAAAAAAAAB8AAAH+AAAAAAAAAAAAAAAAAAAD//////gAAAAAAP///gAAAAAAAAAAfQAAcwAAAAAAAAAAAAAAAAAAA//////wAAAAAAD///4AAAAAAAAAAAIgAAGAMAAAAAAAAAAAAAAAAAH/////4AAAAAAA////AAAAAAAAAAAAQAAAAAEAAAAAAAAAAAAAAAAB/////+AAAAAAAP///yAAAAAAAAAAAACgIAAAAAAAAAAAAAAAAAAAAP/////AAAAAAAH///8BAAAAAAAAAAAA+DAAAAAAAAAAAAAAAAAAAAD/////gAAAAAAB////AYAAAAAAAAAAAfwwAAAAAAAAAAAAAAAAAAAAf////4AAAAAAAf///wOAAAAAAAAAAB/4OAAAgAAAAAAAAAAAAAAAAB////+AAAAAAAP///4fAAAAAAAAAAAf/DgAAEAAAAAAAAAAAAAAAAAH////gAAAAAAD///8HwAAAAAAAAAAf/98AAAAIAAAAAAAAAAAAAAAB////4AAAAAAAf//8B8AAAAAAAAAAP///AAAAAAAAAAAAAAAAAAAAAP///+AAAAAAAH//+AeAAAAAAAAAAH///4AAAAAAAAAAAAAAAAAAAAD////AAAAAAAA///gHgAAAAAAAAA/////AAIAAAAAAAAAAAAAAAAAA////wAAAAAAAH//4D4AAAAAAAAAP////4AAAAAAAAAAAAAAAAAAAAf///AAAAAAAAB///AcAAAAAAAAAH/////AAAAAAAAAAAAAAAAAAAAH///AAAAAAAAAf//gHAAAAAAAAAB/////4AAAAAAAAAAAAAAAAAAAB///gAAAAAAAAH//wAgAAAAAAAAAf/////AAAAAAAAAAAAAAAAAAAAf//4AAAAAAAAB//4AAAAAAAAAAAH/////wAAAAAAAAAAAAAAAAAAAH//+AAAAAAAAAP/+AAAAAAAAAAAB/////8AAAAAAAAAAAAAAAAAAAB///AAAAAAAAAB//gAAAAAAAAAAAP/////gAAAAAAAAAAAAAAAAAAAf//wAAAAAAAAAf/wAAAAAAAAAAAD/////wAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAD/4AAAAAAAAAAAA/////8AAAAAAAAAAAAAAAAAAAD//8AAAAAAAAAA/8AAAAAAAAAAAAH/w///AAAAAAAAAAAAAAAAAAAA//+AAAAAAAAAAP+AAAAAAAAAAAAB/ADf/gAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAABgAAAAAAAAAAAAA8AAv/wAAAAAAAAAAAAAAAAAAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAB/8AAAgAAAAAAAAAAAAAAAB//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAf/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAABoAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAB/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAACAAAAAAAAAAAAAAAA/0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAHgAAAAAAAAAAAAAAAL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAADgAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAABgAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAfAAAAH///+D5/9AAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAP///wB/////////+AAAAAAAAAAAAAAAAAAAADPgAAAAAAAAAAAAAYf///8B///////////8AAAAAAAAAAAAAAAAAAAr4AAAAAAAAQAlpEf////8H////////////6AAAAAAAAAAAAAAAAAAe+AAAAAAAV+//////////H//////////////wAAAAAAAAAAAAAgAAHPwAAAAABH///////////3//////////////wAAAAAAAAAgAAF//z3/8AAAAAEf//////////////////////////wAAAAAAABp//sAf////+AAAAAAP//////////////////////////gAAAAAAD///////////4AAAAAH///////////////////////////4AAAAAAI//////////wAAAAAA////////////////////////////+AAAAAD///////////wAAAD4D/////////////////////////////yAAAAAB//////////8DQAB/Ax////////////////////////////gAAAAPAP//////////4B+D+AA////////////////////////////oAAAAAAf////////////8AAB/////////////////////////////+AAAAAIH/////////////A/////////////////////////////////AAAAAP////////////////////////////////////////////////4AAH/////////////////////////////////////////////////////w/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==";

const W = 320;
const H = 160;
const ROW_BYTES = W / 8; // 40
const R = 0.38; // dot radius

/**
 * Decode the base64 bitmap into a single SVG path string.
 * Each land dot becomes a tiny circle arc at (x+0.5, y+0.5).
 * Using "M cx-r,cy a r,r 0 1,0 d,0 a r,r 0 1,0 -d,0" for each dot.
 * This is ~50× fewer DOM nodes than individual <circle> elements.
 */
function buildPathString(offsetX = 0) {
  const bin = atob(MAP_B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);

  const d = R * 2;
  const parts = [];
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (bytes[y * ROW_BYTES + (x >> 3)] & (128 >> (x & 7))) {
        const cx = x + offsetX + 0.5;
        const cy = y + 0.5;
        // Full circle via two arcs
        parts.push(`M${cx - R},${cy}a${R},${R} 0 1,0 ${d},0a${R},${R} 0 1,0 -${d},0`);
      }
    }
  }
  return parts.join("");
}

const DotWorldMap = memo(function DotWorldMap({ opacity = 0.18 }) {
  const paths = useMemo(() => ({
    left: buildPathString(-320),
    center: buildPathString(0),
    right: buildPathString(320),
  }), []);

  return (
    <svg viewBox="0 0 320 160" className="w-full h-full" style={{ opacity }} preserveAspectRatio="xMidYMid slice">
      <style>{`
        @keyframes mapPan {
          from { transform: translateX(0); }
          to { transform: translateX(320px); }
        }
        .mapPanG {
          animation: mapPan 60s linear infinite;
        }
      `}</style>
      <g className="mapPanG">
        <path d={paths.left} fill="white" />
        <path d={paths.center} fill="white" />
        <path d={paths.right} fill="white" />
      </g>
    </svg>
  );
});

export default DotWorldMap;
